import type { Metadata } from "next";
import { Oswald } from "next/font/google";
import "./globals.css";
import Sidebar from "../components/sidebar";
import { NextIntlClientProvider } from "next-intl";
import { getLocale } from "next-intl/server";
import type { Viewport } from "next";

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  viewportFit: "cover",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const locale = await getLocale();
  return (
    <html lang={locale} className={`${oswald.variable} h-full antialiased`}>
      <body className="min-h-full flex">
        <NextIntlClientProvider>
          <Sidebar />
          <main className="flex-1 flex justify-center items-center px-2 py-2 min-[1280px]:ml-72 xl:ml-80 2xl:ml-96">
            <div className="w-full max-w-300">{children}</div>
          </main>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
